name: Create k3s on macos

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install k3s
        run: |
          curl -sfL https://get.k3s.io | sh -