name: Create k3s on macos

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1

      - name: install kubectl
        uses: azure/setup-kubectl@v3

      - uses: AbsaOSS/k3d-action@v2
        name: "Create Single Cluster"
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb