name: Create k3s on ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: AbsaOSS/k3d-action@v2
        name: "Create Single Cluster"
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 0
            --no-lb

      - name: run commands
        run: |
          free -h
          kubectl get nodes
          kubectl describe node k3d-test-cluster-1-server-0
          kubectl run nginx --image=nginx
          sleep 20s
          kubectl get pods -A -o wide