name: Create k3s on ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: k3s install
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

      - name: run commands
        run: |
          until kubectl get --raw='/readyz?verbose'; do echo "wait for k3s to finish"; done
          free -h
          kubectl get nodes
          kubectl describe node k3d-test-cluster-1-server-0
          sleep 10s
          kubectl run nginx --image=nginx
          sleep 20s
          kubectl get pods -A -o wide